### PR TITLE
Change to use tab indentation (jsbeautifier.org)

### PR DESCRIPTION
**Pull request by u01jmg3**
Change to correct beginning comment block to contain version
Removal of trailing whitespace from entire file

### CODE REVIEW

**Comment by u01jmg3** [comment]
Is this PR worthwhile?

**Comment by tiff** [comment]
sorry, I'm not a fan of hard tabs. thx anyway

**Comment by u01jmg3** [comment]
It was more that there was a mixture of tabs and spaces...

**Comment by tiff** [comment]
already cleaned it up. thx!

**Pull request closed without merging**
